In [1]:
#1.  Implement	naive bayes classification  algorithm	using	Python /R to perform classification on a given dataset.

#2. Compute Confusion Matrix of findTP,FP,TN,FN,Accuracy, Error Rate, Precision,Recall on the given dataset



In [27]:
import pandas as pd
import numpy as np

In [28]:
df=pd.read_csv("Iris (2).csv")

In [29]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [30]:
df.head(4)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa

In [31]:
df.tail(4)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [32]:
df.shape

(150, 6)

In [33]:
df.size

900

In [34]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [36]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [37]:
#extrating X and Y
X=df.iloc[:,1:5]
Y=df.iloc[:,[-1]]

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.40,random_state=False)


In [39]:
print(x_test,y_test,x_train,y_train)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
114            5.8           2.8            5.1           2.4
62             6.0           2.2            4.0           1.0
33             5.5           4.2            1.4           0.2
107            7.3           2.9            6.3           1.8
7              5.0           3.4            1.5           0.2
100            6.3           3.3            6.0           2.5
40             5.0           3.5            1.3           0.3
86             6.7           3.1            4.7           1.5
76             6.8           2.8            4.8           1.4
71             6.1           2.8            4.0           1.3
134            6.1           2.6            5.6           1.4
51             6.4           3.2            4.5           1.5
73             6.1           2.8            4.7           1.2
54             6.5           2.8            4.6           1.5
63             6.1           2.9            4.7           1.4
37      

In [40]:
#now selecting the model ie Gaussian Navie Bayes


In [41]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

/home/sauravmuke/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [42]:
y_pred=nb.predict(x_test)

In [43]:
#checking the accuracy and confusion matrix


In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [45]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy: ",accuracy*100)

Accuracy:  93.33333333333333


In [48]:
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix: ")
print(cm)

Confusion Matrix: 
[[16  0  0]
 [ 0 23  0]
 [ 0  4 17]]


In [50]:
#for iris setosa
print("Iris-setosa")
tp=cm[0][0]
fn=cm[0][1]+cm[0][2] #all elements in row except the tp one
tn=cm[1][1]+cm[1][2]+cm[2][2]+cm[2][1] # all elemets that does not connect to iris setosa by either row or column
fp=cm[1][0]+cm[2][0] #all elements in the collumn expect tp
print("TP ",tp)
print("FP ",fp)
print("TN ",tn)
print("FN ",fn)
total=tp+fn+tn+fp
error_rate=(fp+fn)/total
print("Error Rate",error_rate)

Iris-setosa
TP  16
FP  0
TN  44
FN  0
Error Rate 0.0


In [52]:
#for iris versicolor
print("Iris-versicolor")
tp=cm[1][1]
fn=cm[1][0]+cm[1][2]
tn=cm[0][0]+cm[0][2]+cm[2][0]+cm[2][2]
fp=cm[0][1]+cm[2][1]
print("TP ",tp)
print("FP ",fp)
print("TN ",tn)
print("FN ",fn)
total=tp+fn+tn+fp
error_rate=(fp+fn)/total
print("Error Rate",error_rate)

Iris-versicolor
TP  23
FP  4
TN  33
FN  0
Error Rate 0.06666666666666667


In [54]:
#for iris virginica
print("Iris-virginica")
tp=cm[2][2]
fn=cm[2][0]+cm[2][1]
tn=cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1]
fp=cm[0][1]+cm[0][2]
print("TP ",tp)
print("FP ",fp)
print("TN ",tn)
print("FN ",fn)
total=tp+fn+tn+fp
error_rate=(fp+fn)/total
print("Error Rate",error_rate)

Iris-virginica
TP  17
FP  0
TN  39
FN  4
Error Rate 0.06666666666666667


In [55]:
class_report=classification_report(y_test,y_pred)
print(class_report)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.85      1.00      0.92        23
 Iris-virginica       1.00      0.81      0.89        21

       accuracy                           0.93        60
      macro avg       0.95      0.94      0.94        60
   weighted avg       0.94      0.93      0.93        60

